### ISSUE TITLE
Candlestick Pattern

### ISSUE THREAD

**Issue by afifabroory** [suparjotamin/stockie#1]
Hello :smiley:!

Previously thank you, this project is quite good and useful
especially the logic program ... Can find the candlestick pattern

I want to ask...
Is there an article reference, or etc. a logic program in function **is_pattern ()** Candlestick.py?

thank you

**Comment by suparjotamin** [comment]
Halo Pak Afif,

Terima kasih, saya turut senang karya saya bisa membantu. Untuk referensi
candlesticknya, saya menggunakan website incrediblecharts.com sebagai
referensi utama, referensi pelengkap cukup banyak.

Untuk logical dibaliknya, saya membuat sendiri. Dan untuk quality control
dan penentuan parameternya, saya menggenerate gambar candle dan melakukan
screening untuk mengecek apakah pattern yang diinginkan sudah sesuai,
Karena memang sejauh yang saya pelajari tidak ada rumus/formula baku untuk
pattern candlestick.

Terima kasih

**Comment by afifabroory** [comment]
Baik terima kasih, saya kira ada rumus bakunya :hear_no_evil:
